spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.106.127.25:3306/baseproject
    username: test
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource  #默认使用TomcatJDBD DataSource
  application:
    name: spring-cloud-eureka
  #文件上传
  http:
    multipart:
      enabled: true   # 启用http上传处理
      max-file-size: 100MB # 设置单个文件的最大长度
      max-request-size: 100MB # 设置最大的请求文件的大小
      file-size-threshold: 1MB  # 当上传文件达到1MB的时候进行磁盘写入
      location: /  # 上传的临时目录
  #视图模型解析,静态资源后缀配置
  mvc:
    view:
      prefix: /static/
      suffix: .html
server:
  port: 8000
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/

